### ISSUE TITLE
Error-Message in Adapter

### ISSUE THREAD

**Issue by jhg28** [TA2k/ioBroker.viessmannapi#50]
Starting today I receive the following messages:

**admin.0**
2024-01-01 19:16:50.409	error	Cannot subscribe "viessmannapi.0.2157277.0.general.roles.type:product;Vitocal_250A": Error The pattern "viessmannapi.0.2157277.0.general.roles.type:product;Vitocal_250A" is not a valid ID pattern
**host.iobroker-Server**
2024-01-01 19:16:50.394	warn	States 127.0.0.1:55310 Error from InMemDB: Error: The pattern "viessmannapi.0.2157277.0.general.roles.type:product;Vitocal_250A" is not a valid ID pattern at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2470:15) at StatesInMemoryServer.handleSubscribe (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/inMemFileDB.ts:324:59) at StatesInMemoryServer._subscribeForClient (/opt/iobroker/node_modules/@iobroker/db-states-file/src/lib/states/statesInMemFileDB.js:258:14) at RedisHandler.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-states-jsonl/src/lib/states/statesInMemServerRedis.js:395:26) at RedisHandler.emit (node:events:514:28) at RedisHandler.emit (node:domain:489:12) at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/redisHandler.ts:209:37) at processImmediate (node:internal/timers:476:21)

**admin.0**
2024-01-01 19:16:50.389	error	Invalid pattern on subscribe: The pattern "viessmannapi.0.2157277.0.general.roles.type:product;Vitocal_250" is not a valid ID pattern

I use ViCare+ in the moment to see if the additional data brings any benefit.

Maybe this creates the error messages.
Additionally it looks like, that Viessmann changed something in the data.

**Comment by TA2k** [comment]
With v2.4.0 ?
