### ISSUE TITLE
Keine Objektdaten für Wärmepumpe Vitocal 262-A Typ T2H-R290 bei der 2. Instanz/Installation mit 2 Gateways  

### ISSUE THREAD

**Issue by nofuntoday** [TA2k/ioBroker.viessmannapi#53]
Im Iobroker Objektbaum werden für meine Wärmepumpe Vitocal 262-A Typ T2H-R290 keine Daten angelegt. 
Ist eine 2 "Installation" mit 2 Gateways (siehe Log).  

Die Daten sind sind mit folgenen Link direkt abrufbar und korrekt: 
https://api.viessmann.com/iot/v2/features/installations/2..../gateways/7......./devices/0/features
https://api.viessmann.com/iot/v2/features/installations/2...../gateways/7......./devices/0/features/heating.dhw.oneTimeCharge
......
Natürlich alle mit gültigen Viessmann API Access Token. 

Log: 
.....
viessmannapi.0 | 2024-05-03 10:58:34.508 | warn | Found 2 online gateways select 1 gateway.
viessmannapi.0 | 2024-05-03 10:58:34.507 | info | Filter out offline gateways.
viessmannapi.0 | 2024-05-03 10:58:34.507 | info | Found 2 gateways for installation
viessmannapi.0 | 2024-05-03 10:58:33.798 | info | 2 installations found.
viessmannapi.0 | 2024-05-03 10:58:30.999 | info | starting. Version 2.4.0 in /opt/iobroker/node_modules/iobroker.viessmannapi, node: v18.20.0, js-controller: 5.0.19
......

Auch mit einer 2 angelegten Instant im Iobroker mit "Index of Which Gateway shall be use: 2" funktioniert es nicht. 
Kann gerne weiter Information liefern. 

**Versions:**  
 - Adapter version: 2.4.0 
 - JS-Controller version:  5.0.19
 - Node version: v18.20.0
 - Operating system: raspberrypi3 6.1.21-v8+

**Comment by TA2k** [comment]
index 1 getestet?

**Comment by nofuntoday** [comment]
Adapter läuft mit "Index of Which Gateway shall be use: 1" standardmäßig für meine Standardheizung mit VitoconnectOPTO2. 
Neu jetzt Gateway Typ TCU101 als 2. Gateway.

**Comment by TA2k** [comment]
hast du 0 und 1 probiert

**Comment by nofuntoday** [comment]
Ich habe jetzt 0 getestet, geht nicht.  Hier der Log: 

host.raspberrypi3
2024-05-03 12:03:07.058	warn	Do not restart adapter system.adapter.viessmannapi.0 because restart loop detected
host.raspberrypi3
2024-05-03 12:03:07.058	info	Restart adapter system.adapter.viessmannapi.0 because enabled
host.raspberrypi3
2024-05-03 12:03:07.057	error	instance system.adapter.viessmannapi.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

viessmannapi.0
2024-05-03 12:03:06.774	info	terminating

viessmannapi.0
2024-05-03 12:03:06.271	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

viessmannapi.0
2024-05-03 12:03:06.269	info	terminating

viessmannapi.0
2024-05-03 12:03:06.258	error	Cannot read properties of undefined (reading 'devices')

viessmannapi.0
2024-05-03 12:03:06.257	error	TypeError: Cannot read properties of undefined (reading 'devices') at Viessmannapi.getDeviceIds (/opt/iobroker/node_modules/iobroker.viessmannapi/main.js:212:36) at runNextTicks (node:internal/process/task_queues:60:5) at process.processImmediate (node:internal/timers:447:9) at async Viessmannapi.onReady (/opt/iobroker/node_modules/iobroker.viessmannapi/main.js:66:7)

viessmannapi.0
2024-05-03 12:03:06.256	error	unhandled promise rejection: Cannot read properties of undefined (reading 'devices')

viessmannapi.0
2024-05-03 12:03:06.255	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

viessmannapi.0
2024-05-03 12:03:06.236	info	2 installations found.

viessmannapi.0
2024-05-03 12:03:03.377	info	starting. Version 2.4.0 in /opt/iobroker/node_modules/iobroker.viessmannapi, node: v18.20.0, js-controller: 5.0.19


Mit 1 laufen die 2 "alten" VitoconnectOPTO2, aber keine Daten von der Vitocal.

**Comment by TA2k** [comment]
dann einfach debug log aktivieren und schauen

**Comment by nofuntoday** [comment]
Anliegend das Debug-Log. Gibt für mich keine Erkenntnisse, evtl. macht die Struktur hier Probleme:  2 installionid*s, 3 gatewaySerial, 2 gatewqayType.  

Vielen Dank im Voraus für deine Bemühungen !!  Super Job für die Community !!!

**Comment by TA2k** [comment]
die GitHub version installieren und nochmal Testen mit logs

**Comment by nofuntoday** [comment]
Neue GitHub Version installiert, hat den Fortschritt gebracht das die Fehlermeldung bei Wechsel auf index 0 und 2 weg sind !!! Super !! Jedoch baut er nach wie vor nur die Daten von 
https://api.viessmann.com/iot/v1/features/installations/242858/gateways/7637415030574198/devices/0/features
https://api.viessmann.com/iot/v1/features/installations/1964349/gateways/7637415014142221/devices/0/features 
auf. 
Die Daten für
https://api.viessmann.com/iot/v2/features/installations/242858/gateways/7949720002228231/devices/0/features
fehlen immer noch, auch wenn ich den Index verändere. 
Bei Index 0 werden 289 Objekte aufgebaut, bei Index 1 und Index 2 5376 Objekte.

**Comment by nofuntoday** [comment]
Hier noch ergänzend ein Auszug aus dem Debug Log . 

[Log-Viessmann-Adapter-#2.txt](https://github.com/TA2k/ioBroker.viessmannapi/files/15201840/Log-Viessmann-Adapter-.2.txt)

**Comment by TA2k** [comment]
nochmal die GitHub version installieren

**Comment by nofuntoday** [comment]
Version aus GitHub installiert, leider noch kein Erfolg. Keine Fehler im Log, jedoch auch keine Daten für die Vitocal.
Hier der neuerzeugte Objektbaum: 
![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/160725603/4e5e39c2-1865-43c6-adfa-ed9e9e62b1ec)

**Comment by TA2k** [comment]
auf welchem gateway sind denn die geräte bei jsb 42

**Comment by nofuntoday** [comment]
Für JSB42 sind 2 Gateways notwendig:

![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/160725603/4a586ab8-cf86-4ac3-86dc-591566fcc7b8)

**Comment by TA2k** [comment]
und in beiden gateways sind relevante geräte enthalten?

**Comment by nofuntoday** [comment]
Folgender Aufruf: 
https://api.viessmann.com/iot/v1/equipment/installations?includeGateways=true
bringt bei mir folgenden Output: 
[Log-Viessmann-Adapter-#3.txt](https://github.com/TA2k/ioBroker.viessmannapi/files/15209173/Log-Viessmann-Adapter-.3.txt)
Vielleicht klärt das die Gateway Struktur besser.

**Comment by nofuntoday** [comment]
Ja, einer für den Brenner und der andere für die Wärmepumpe.

**Comment by mejzej** [comment]
Hallo,

ich habe die gleiche Konfiguration mit einem Vitorondens (Angeschlossen über VitconnectOPTO2) und einer Vitocal 262-A Typ T2H-R290. Die Einstellung Gateway 2 funktioniert ebenfalls nicht. Da ich aber sowieso Werte von beiden Gateways benötige habe ich die Wärmepumpe als neue Anlage hinzugefügt. In dieser Konfiguration liest der Adpter beim Start die Werte der Vitocal, anschließend erfolgt aber kein Update. werden nur beim Start des Adapters aktualisier anschließend nicht mehr. Ich behelfe mir aktuell mit einem Restart-Cron-Job.  Versions:

Adapter version: 2.4.0
JS-Controller version: 7.0.7
Node version:  v20.18.3
Operating system: raspberrypi4b

[2025-09-14 185500.031 - info viessm.log](https://github.com/user-attachments/files/22322646/2025-09-14.185500.031.-.info.viessm.log)
